application: fridayfilmclub
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /closure-library
  static_dir: closure-library

- url: /javascript
  static_dir: javascript
  
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP 
  login: admin

- url: /admin/?.*
  script: main.app
  login: admin

- url: /question/?.*
  script: main.app
  login: required

- url: /.*
  script: main.app

builtins:
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?data/.*
- ^(.*/)?javascript/.*
- ^(.*/)?scripts/.*