// @ use_closure_library=true
// Copyright 2011 Friday Film Club All Rights Reserved.

/**
 * @fileoverview Auto complete for Movies data.
 */
goog.provide('ffc.AutoComplete')

goog.require('goog.dom')
goog.require('goog.ui.AutoComplete.Renderer')
goog.require('goog.ui.AutoComplete.RichInputHandler')
goog.require('goog.ui.AutoComplete')

goog.require('ffc.RemoteArrayMatcher');



/**
 * AutoComplete constructor.
 * @constructor
 */
ffc.AutoComplete = function(el, elKey) {
  // Create a custom renderer that renders rich rows.  The renderer calls
  // row.render(node, token) for each row.
  var customRenderer = {};
  customRenderer.renderRow = function(row, token, node) {
    return row.data.render(node, token);
  };

  var keyInput = goog.dom.getElement(elKey); 
  this.keyInput = keyInput;

  /**
   * A standard renderer that uses a custom row renderer to display the
   * rich rows generated by this autocomplete widget.
   * @type {goog.ui.AutoComplete.Renderer}
   * @private
   */
  var renderer = new goog.ui.AutoComplete.Renderer(null, customRenderer);
  this.renderer_ = renderer;

  var matcher = new ffc.RemoteArrayMatcher(ffc.AutoComplete.API_URL_, keyInput);
  this.matcher_ = matcher;

  var inputhandler = new goog.ui.AutoComplete.RichInputHandler(null, null,
      false, 300);

  goog.ui.AutoComplete.call(this, matcher, renderer, inputhandler);

  inputhandler.attachAutoComplete(this);
  inputhandler.attachInputs(el);

}
goog.inherits(ffc.AutoComplete, goog.ui.AutoComplete);
goog.exportSymbol('ffc.AutoComplete', ffc.AutoComplete);


/**
 *
 */
ffc.AutoComplete.prototype.getKeyInput = function() {
  return this.keyInput;
};


/**
 * @private
 */
ffc.AutoComplete.prototype.dismiss = function() {
  if (!this.selectionHandler_.getActiveElement()) {
    this.keyInput = '';
  }
   goog.base(this, 'dismiss');
};
 


/**
 * @private
 */
ffc.AutoComplete.API_URL_ = '/suggest';
