application: ffcapp
version: default
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static/js/src/
  static_dir: .

- url: /static
  static_dir: static

- url: /closure-library
  static_dir: lib/closure-library

- url: /closure-templates
  static_dir: lib/closure-templates

- url: /javascript
  static_dir: javascript

- url: /growjs
  static_dir: lib/growjs

- url: /less
  static_dir: lib/less

- url: /lib/twitter
  static_dir: lib/twitter
  mime_type: text/css

- url: /fonts
  static_dir: lib/twitter/fonts

- url: /stylesheets
  static_dir: stylesheets
  mime_type: text/css
  
- url: /admin/?.*
  script: main.app
  login: admin

- url: /tasks/?.*
  script: main.app
  login: admin

- url: /.*
  script: main.app

builtins:
- remote_api: on
- deferred: on

inbound_services:
- channel_presence

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?fabfile\.py
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?lib/closure-library/closure/bin/.*
- ^(.*/)?lib/closure-library/.*\.data$
- ^(.*/)?lib/closure-templates/buildtools/.*
- ^(.*/)?lib/closure-templates/examples/.*
- ^(.*/)?lib/closure-templates/java/.*
- ^(.*/)?lib/closure-templates/javadoc-complete/.*
- ^(.*/)?lib/closure-templates/javadoc-lite/.*
- ^(.*/)?lib/closure-templates/javascript/examples/.*
- ^(.*/)?lib/closure-templates/testdata/.*
- ^(.*/)?lib/closure-templates/.*txt
- ^(.*/)?lib/closure-templates/.*xml
- ^(.*/)?lib/twitter/_config.yml$
- ^(.*/)?README(.md)?$
- ^(.*/)?AUTHORS$
- ^(.*/)?CONTRIBUTING(.md)?$
- ^(.*/)?CHANGELOG(.md)?$
- ^(.*/)?LICENSE$
- ^(.*/)?COPYING$
- ^(.*/)?CNAME$
- ^(.*/)?DOCS-LICENSE$
- ^(.*/)?LICENSE-MIT$
