application: ffcapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: lxml
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /closure-library
  static_dir: closure-library

- url: /closure-templates
  static_dir: closure-templates

- url: /javascript
  static_dir: javascript

- url: /growjs
  static_dir: growjs

- url: /(.*\.less)
  mime_type: text/css
  static_files: \1
  upload: (.*\.less)

- url: /less
  static_dir: less

- url: /twitter-bootstrap
  static_dir: twitter-bootstrap

- url: /fonts
  static_dir: twitter-bootstrap/fonts

- url: /stylesheets
  static_dir: stylesheets
  
- url: /admin/?.*
  script: main.app
  login: admin

- url: /question/?.*
  script: main.app

- url: /.*
  script: main.app

builtins:
- remote_api: on
- datastore_admin: on
- deferred: on

inbound_services:
- channel_presence

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?fabfile\.py
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?closure-library/closure/bin/.*
- ^(.*/)?closure-library/.*\.data$
- ^(.*/)?closure-templates/buildtools/.*
- ^(.*/)?closure-templates/examples/.*
- ^(.*/)?closure-templates/java/.*
- ^(.*/)?closure-templates/javadoc-complete/.*
- ^(.*/)?closure-templates/javadoc-lite/.*
- ^(.*/)?closure-templates/javascript/examples/.*
- ^(.*/)?closure-templates/testdata/.*
- ^(.*/)?closure-templates/.*txt
- ^(.*/)?closure-templates/.*xml
- ^(.*/)?less/bin/.*
- ^(.*/)?less/build/build.yml
- ^(.*/)?less/test/browser/test-runner-template.tmpl
- ^(.*/)?twitter-bootstrap/_config.yml$
- ^(.*/)?README(.md)?$
- ^(.*/)?AUTHORS$
- ^(.*/)?CONTRIBUTING(.md)?$
- ^(.*/)?CHANGELOG(.md)?$
- ^(.*/)?LICENSE$
- ^(.*/)?COPYING$
- ^(.*/)?CNAME$
- ^(.*/)?DOCS-LICENSE$
- ^(.*/)?LICENSE-MIT$
